sudo: required
services:
  - docker

before_install:
  - docker build -t edan13l/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true edan13l/react-test npm test

after_success:
  - docker build -t edan13l/multi-client ./client
  - docker build -t edan13l/multi-nginx ./nginx
  - docker build -t edan13l/multi-server ./server
  - docker build -t edan13l/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push  edan13l/multi-client
  - docker push  edan13l/multi-nginx
  - docker push  edan13l/multi-server
  - docker push  edan13l/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  name: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-671919719178"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
